#!sh

SCRIPTS_DIR='./shell/scripts'

# ~~~~~~~~~~~~~~~ Ensure zsh ~~~~~~~~~~~~~~~~
# Check if zsh is installed and if not, install it.
# This is only sw that is needed to be installed before running the setup script, that will install the rest of the software.

echo "Checking if zsh is installed..."
if ! command -v zsh &> /dev/null; then
    echo "Zsh is not installed. Installing..."
    paru -S zsh
else
    echo "Zsh is already installed."
fi

# ~~~~~~~~~~~~~~~ Set all scripts as executable ~~~~~~~~~~~~~~~~

echo "Setting all scripts in $SCRIPTS_DIR as executable..."
find "$SCRIPTS_DIR" -type f -exec chmod +x {} \;

# ~~~~~~~~~~~~~~~ Install needed SW ~~~~~~~~~~~~~~~~
# Execute the system setup script with zsh (we are in sh now)

echo "Running system setup script..."
"$SCRIPTS_DIR/system-setup"

# ~~~~~~~~~~~~~~~ Stow the config ~~~~~~~~~~~~~~~~

echo "Stowing the configuration files..."
stow \
        bash \
        brave \
        colors \
        ghostty \
        hyprlock \
        mako \
        niri \
        paru \
        profile \
        shell \
        starship \
        waybar \
        yazi \
    -t ~ \
    $@
    

# ~~~~~~~~~~~~~~~ Restart services that may be affected by config changes ~~~~~~~~~~~~~~~~

makoctl reload

# ~~~~~~~~~~~~~~~ Launch the shell ~~~~~~~~~~~~~~~~

zsh
