#!/usr/bin/env zsh

set -e  # Exit on any command failure

# Get focused window information from niri
local window_info=$(niri msg focused-window)

# Extract App ID and Title using awk
local formatted_text=$(awk -F': ' '
    /App ID/ { appid = $2 }
    /Title/  { title = $2 }
    END {
        gsub(/"/, "", appid)
        gsub(/"/, "", title)
        print "[" appid "] " title
    }
' <<< "$window_info")

# Copy to clipboard
clipse -c <<< "$formatted_text"

# Send notification with newline properly
notify-send -t 3000 "Copied to clipboard:" "$(printf "%b" "\n<tt>$formatted_text</tt>")"
