#!/usr/bin/env zsh

set -e # Exit on any command failure

# ~~~~~~~~~~~~~~~ Load helper functions ~~~~~~~~~~~~~~~

source "$SCRIPT_FNS/log.zsh"

# ~~~~~~~~~~~~~~ Ensure ZSH is the default shell ~~~~~~~~~~~~~~~

local ZSH_PATH=$(which zsh)
if [[ "$SHELL" == "$ZSH_PATH" ]]; then
    log "ZSH is already the default shell. Skipping..."
else
    log "Setting up ZSH as default shell."
    chsh -s "$ZSH_PATH"
fi

# ~~~~~~~~~~~~~~ Ensure that zinit is installed ~~~~~~~~~~~~~~~

local ZINIT_HOME="${ZINIT_HOME:-$HOME/.local/share}/zinit/zinit.git"
if [ ! -d $ZINIT_HOME ]; then
    log "Zinit not found. Cloning into $ZINIT_HOME..."
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
    log "Zinit cloned successfully."
fi

# ~~~~~~~~~~~~~~ Ensure that cargo is installed ~~~~~~~~~~~~~~~

if command -v cargo > /dev/null 2>&1; then
    log "Rust SDK is already installed. Skipping installation."
else
    log "Installing Rust SDK."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# ~~~~~~~~~~~~~~ Paru packages installation  ~~~~~~~~~~~~~~~

paru -S --noconfirm --needed \
    wl-clipboard \
    clipse-bin \
    bat \
    fzf \
    bfs \
    jq \
    dbus \
    mediainfo \
    gdk-pixbuf2 \
    librsvg \
    ffmpegthumbnailer \
    perl-image-exiftool \
    poppler \
    odt2txt \
    catdoc \
    docx2txt \
    gnumeric \
    atool \
    p7zip \
    binutils \
    openssl \
    libcdio \
    kitty \
    ghostty \
    ttf-firacode-nerd \
    doublecmd \
    qt6ct \
    inter-font \
    libqalculate \
    sherlock-launcher-bin \
    hyprpicker \
    jujutsu

# ~~~~~~~~~~~~~~ Cargo packages installation ~~~~~~~~~~~~~~~

cargo install \
    eza \
    zoxide \
    starship

# ~~~~~~~~~~~~~~ Install Bun ~~~~~~~~~~~~~~~

# Run bun install script if bun is not installed

if command -v bun > /dev/null 2>&1; then
    log "Bun is already installed. Checking for updates..."
    bun upgrade
else
    log "Installing Bun."
    curl -fsSL https://bun.sh/install | bash
fi

# ~~~~~~~~~~~~~~ Generate completions ~~~~~~~~~~~~~~~

# ~~~~~~~~~~~~~~ Enable systemctl services ~~~~~~~~~~~~~~~
