#!/usr/bin/env zsh

set -e # Exit on any command failure

# Get first UP interface's IPv4 address
ip_addr=$(ip -j addr | jq -r '.[] | select(.operstate=="UP") | .addr_info[] | select(.family=="inet") | .local' | head -1)

if [[ -n "$ip_addr" ]]; then
    # Copy to clipboard
    echo -n "$ip_addr" | clipse -c
    
    # Notify user
    notify-send -t 3000 "IP address copied to clipboard:" "$(printf "%b" "\n<tt>$ip_addr</tt>")"
else
    notify-send -t 3000 "Error" "No IP address found"
    exit 1
fi
