#!/usr/bin/env zsh

set -e # Exit on any command failure

local container_id=$1
local init_command=$2
local shell_cmd="/bin/sh"

# Try to use bash if available in container
if docker exec $container_id which bash > /dev/null 2>&1; then
    shell_cmd="/bin/bash"
fi

if [ -n "$init_command" ]; then
    final_cmd="docker exec -it $container_id $shell_cmd -c \"$init_command && $shell_cmd\""
    echo -e "\033[35m\$\033[0m $final_cmd"
    docker exec -it $container_id $shell_cmd -c "$init_command && $shell_cmd"
else
    final_cmd="docker exec -it $container_id $shell_cmd"
    echo -e "\033[35m\$\033[0m $final_cmd"
    docker exec -it $container_id $shell_cmd
fi
