#!/bin/bash

options=("Shutdown" "Reboot" "Suspend" "Hibernate" "Logout" "Cancel")

choice=$(printf "%s\n" "${options[@]}" | sherlock)

case $choice in
    Shutdown)
        shutdown now
        ;;
    Reboot)
        reboot
        ;;
    Suspend)
        systemctl suspend
        ;;
    Hibernate)
        systemctl hibernate
        ;;
    Logout)
        loginctl terminate-user "$USER"
        ;;
    *)
        # Cancel or no selection
        exit 0
        ;;
esac
