#!/usr/bin/env bash

source "$SCRIPT_FNS/run_bash_tpl.zsh"

echo "Regenerating dotfiles..."
run_bash_tpl "$CONFIGURATION_DIR"

dms restart

echo "Setting all scripts in $SCRIPTS as executable..."
find "$SCRIPTS" -type f -exec chmod +x {} \;

echo "Reloading ZSH completions..."
autoload -Uz compinit && compinit

echo "Entering new shell..."
zsh
