#!/usr/bin/env bash

source "$SCRIPT_FNS/run_bash_tpl.zsh"

echo "Regenerating dotfiles..."
run_bash_tpl "$TEMPLATE_DIR" "$GENERATED_DIR"

echo "Reloading mako..."
makoctl reload

echo "Reloading waybar..."
killall  waybar;
setsid waybar >/dev/null 2>&1 &

echo "Setting all scripts in $SCRIPTS as executable..."
find "$SCRIPTS" -type f -exec chmod +x {} \;

echo "Entering new shell..."
zsh
