#!/usr/bin/env zsh

source "$SCRIPT_FNS/log.zsh"

function _main() {
    
    # prepare directories
    # -------------------
    
    local main_directory="$HOME/.zen"
    local install_directory="$main_directory/zen"
    
    # Remove installation directory
    # ---------------------------
    
    if [ -d "$install_directory" ]; then
        log -f "Removing Zen installation directory"
        rm -rf "$install_directory"
    fi
    
    # Remove symbolic link
    # -------------------
    
    if [ -L "$HOME/.local/bin/zen" ]; then
        log -f "Removing Zen executable link"
        rm -f "$HOME/.local/bin/zen"
    fi
    
    # Remove desktop entry
    # -------------------
    
    if [ -f "$HOME/.local/share/applications/zen.desktop" ]; then
        log -f "Removing Zen desktop entry"
        rm -f "$HOME/.local/share/applications/zen.desktop"
    fi
    
    # Remove cache directory
    # ---------------------
    
    if [ -d "$HOME/.cache/zen" ]; then
        log -f "Removing Zen cache directory"
        rm -rf "$HOME/.cache/zen"
    fi
    
    # Clean up Sine related files
    # --------------------------
    
    log -f "Checking for Sine related files"
    
    # Check for Sine config in profile directory
    local profile_dirs=("$main_directory/zen-browser/profile" "$main_directory/profile")
    for profile_dir in "${profile_dirs[@]}"; do
        if [ -d "$profile_dir/chrome/utils" ]; then
            log -f "Removing Sine configuration from $profile_dir"
            rm -rf "$profile_dir/chrome/utils"
        fi
    done
    
    # Clean up main directory if empty
    # ------------------------------
    
    if [ -d "$main_directory" ] && [ -z "$(ls -A "$main_directory")" ]; then
        log -f "Removing empty Zen configuration directory"
        rm -rf "$main_directory"
    fi
    
    log -f "Zen uninstallation completed"
}

_main "$@"
exit $?
