import { AppConfig } from '../utils/app_manager';

export const zenBrowserConfig: AppConfig = {
    id: 'zen-browser',
    name: 'Zen Browser',
    repository: 'zen-browser/desktop',
    assetPattern: 'linux-x86_64.tar.xz',
    paths: {
        mainDirectory: '$HOME/.zen',
        installDirectory: '$HOME/.zen/zen',
        executableLink: '$HOME/.local/bin/zen',
        executableTarget: '$HOME/.zen/zen/zen',
        desktopFile: '$HOME/.local/share/applications/zen.desktop',
        iconPath: '$HOME/.zen/zen/browser/chrome/icons/default/default128.png',
        cacheDirectories: ['$HOME/.cache/zen'],
        profileDirectories: ['$HOME/.zen/zen-browser/profile', '$HOME/.zen/profile'],
    },
    backup: {
        defaultBaseName: 'zen-browser-backup',
        preInstallBackupName: 'zen-browser-backup-before-installation',
        environmentVariable: 'SYNCED_BACKUP_DIR',
        excludePatterns: ['zen/*', '*.tar.gz', '*.zip', '*/storage/**'],
        includeAllSuffix: 'complete',
    },
    desktopEntry: {
        version: '1.0',
        name: 'Zen Browser',
        comment: 'Experience tranquillity while browsing the web without people tracking you!',
        genericName: 'Web Browser',
        keywords: ['Internet', 'WWW', 'Browser', 'Web', 'Explorer'],
        exec: '$HOME/.local/bin/zen',
        terminal: false,
        type: 'Application',
        icon: '$HOME/.zen/zen/browser/chrome/icons/default/default128.png',
        categories: ['GNOME', 'GTK', 'Network', 'WebBrowser'],
        mimeType: [
            'text/html',
            'text/xml',
            'application/xhtml+xml',
            'application/rss+xml',
            'application/rdf+xml',
            'image/gif',
            'image/jpeg',
            'image/png',
            'x-scheme-handler/http',
            'x-scheme-handler/https',
            'x-scheme-handler/ftp',
            'x-scheme-handler/chrome',
            'video/webm',
            'application/x-xpinstall',
        ],
        startupNotify: true,
        additionalFields: {
            'X-MultipleArgs': 'false',
        },
    },
};
