import { AppConfig } from '../app_manager';

export const zen_browser_config: AppConfig = {
    id: 'zen-browser',
    name: 'Zen Browser',
    repository: 'zen-browser/desktop',
    asset_pattern: 'linux-x86_64.tar.xz',
    paths: {
        main_directory: '$HOME/.zen',
        install_directory: '$HOME/.zen/zen',
        executable_link: '$HOME/.local/bin/zen',
        executable_target: '$HOME/.zen/zen/zen',
        desktop_file: '$HOME/.local/share/applications/zen.desktop',
        icon_path: '$HOME/.zen/zen/browser/chrome/icons/default/default128.png',
        cache_directories: ['$HOME/.cache/zen'],
        profile_directories: ['$HOME/.zen/zen-browser/profile', '$HOME/.zen/profile'],
    },
    backup: {
        default_base_name: 'zen-browser-backup',
        pre_install_backup_name: 'zen-browser-backup-before-installation',
        environment_variable: 'SYNCED_BACKUP_DIR',
        exclude_patterns: ['zen/*', '*.tar.gz', '*.zip', '*/storage/**'],
        include_all_suffix: 'complete',
    },
    desktop_entry: {
        version: '1.0',
        name: 'Zen Browser',
        comment: 'Experience tranquillity while browsing the web without people tracking you!',
        generic_name: 'Web Browser',
        keywords: ['Internet', 'WWW', 'Browser', 'Web', 'Explorer'],
        exec: '$HOME/.local/bin/zen',
        terminal: false,
        type: 'Application',
        icon: '$HOME/.zen/zen/browser/chrome/icons/default/default128.png',
        categories: ['GNOME', 'GTK', 'Network', 'WebBrowser'],
        mime_type: [
            'text/html',
            'text/xml',
            'application/xhtml+xml',
            'application/rss+xml',
            'application/rdf+xml',
            'image/gif',
            'image/jpeg',
            'image/png',
            'x-scheme-handler/http',
            'x-scheme-handler/https',
            'x-scheme-handler/ftp',
            'x-scheme-handler/chrome',
            'video/webm',
            'application/x-xpinstall',
        ],
        startup_notify: true,
        additional_fields: {
            'X-MultipleArgs': 'false',
        },
    },
};
