[mgr]
show_hidden = true

[general]
linemode = "size_and_mtime"

# [linemode]
# custom = [
# 	{ name = "permissions" },
# 	{ name = "size" },
# 	{ name = "mtime" }
# ]

[opener]
code = [{ run = 'code "$@"', block = true }]
